### PR TITLE
Commit Transfer

### PR DESCRIPTION
**Pull request by zackshapiro**
Added this at the suggestion of Jori and John. This allows users to turn their pending buys/sells into completed ones by posting to `/transfers/:id/commit`

Updated the version based on a dependency error I got from `omniauth-ruby` asking for a `coinbase` version of 3 or greater

### CODE REVIEW

**Comment by aianus** [comment]
Hi Zack,

Could you add a test for this please?

**Comment by zackshapiro** [comment]
Yep

Best,
Zack

**Comment by zackshapiro** [comment]
@aianus added tests, would you take a look at the fakeweb request on the one that's failing. Not sure if I'm registering it wrong by registering the `id` of the transaction with fakeweb before I run it or it's something else.

**Comment by aianus** [comment]
Rebased on v3 as ea2e5c0c34a663fc9c7cad6ca58cb8938456330b

Make sure you pull the latest commits on v3, I think you're on an old commit because the version was already changed in version.rb a while ago.

**Pull request closed without merging**
